# Generated by Django 5.2.1 on 2025-05-10 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_challenges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
